# Generated by Django 6.0.7 on 2026-08-07 14:08

import apps.authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_address_user_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=14, validators=[apps.authentication.utils.validate_number]
            ),
        ),
    ]
